### ISSUE TITLE
Maven install does't work with JDK 11

### ISSUE THREAD

**Issue by ftyers** [Orange-OpenSource/conllueditor#1]
When I try to `mvn install` I get a backtrace:

```
$ mvn install -DskipTests
[INFO] Scanning for projects...
---------------------------------------------------
constituent[0]: file:/usr/share/maven/conf/logging/
constituent[1]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[2]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[3]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[4]: file:/usr/share/maven/lib/guava.jar
constituent[5]: file:/usr/share/maven/lib/guice.jar
constituent[6]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[7]: file:/usr/share/maven/lib/jsr250-api.jar
constituent[8]: file:/usr/share/maven/lib/jcl-over-slf4j.jar
constituent[9]: file:/usr/share/maven/lib/wagon-file.jar
constituent[10]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[11]: file:/usr/share/maven/lib/maven-resolver-provider-3.x.jar
constituent[12]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[13]: file:/usr/share/maven/lib/sisu-inject.jar
constituent[14]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[15]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[16]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[17]: file:/usr/share/maven/lib/maven-shared-utils.jar
constituent[18]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[19]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[20]: file:/usr/share/maven/lib/cdi-api.jar
constituent[21]: file:/usr/share/maven/lib/commons-lang3.jar
constituent[22]: file:/usr/share/maven/lib/maven-resolver-transport-wagon.jar
constituent[23]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[24]: file:/usr/share/maven/lib/maven-resolver-api.jar
constituent[25]: file:/usr/share/maven/lib/maven-slf4j-provider-3.x.jar
constituent[26]: file:/usr/share/maven/lib/slf4j-api.jar
constituent[27]: file:/usr/share/maven/lib/maven-builder-support-3.x.jar
constituent[28]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[29]: file:/usr/share/maven/lib/javax.inject.jar
constituent[30]: file:/usr/share/maven/lib/sisu-plexus.jar
constituent[31]: file:/usr/share/maven/lib/aopalliance.jar
constituent[32]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[33]: file:/usr/share/maven/lib/commons-io.jar
constituent[34]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[35]: file:/usr/share/maven/lib/jansi.jar
constituent[36]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[37]: file:/usr/share/maven/lib/commons-cli.jar
constituent[38]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[39]: file:/usr/share/maven/lib/maven-resolver-impl.jar
constituent[40]: file:/usr/share/maven/lib/maven-resolver-spi.jar
constituent[41]: file:/usr/share/maven/lib/maven-resolver-connector-basic.jar
constituent[42]: file:/usr/share/maven/lib/maven-resolver-util.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/Xpp3DomBuilder$InputLocationBuilder
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:108)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:85)
	at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:89)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:552)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:281)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:414)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:405)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:82)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:507)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.xml.Xpp3DomBuilder$InputLocationBuilder
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 26 more
```

Any thoughts?

I'm using OpenJDK 11:
```
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+4-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.4+4-post-Debian-1, mixed mode, sharing)
```

**Comment by ftyers** [comment]
Updating maven seemed to help!
