### ISSUE TITLE
JNI error on docker image

### ISSUE THREAD

**Issue by gnegrelli** [Orange-OpenSource/conllueditor#8]
Hi!

I'm trying to run the `conllueditor` docker image but I keep having the error below:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/orange/labs/editor/ConlluEditor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

Is there an older image with a version of Java compatible with mine? How can I run it?

BTW, I tried to run the docker image with `docker run [...] conllueditor:latest` (as shown in README), but it only worked with `docker run [...] jheinecke/conllueditor:latest`. Is the documentation outdated? Or is that a different image?

Thanks!

**Comment by jheinecke** [comment]
Hi,
sorry, the 2.7.4 image had a problem, I moved on to JDK 11 for the code but forgot to update the jdk within the image. That's corrected in version 2.7.5 (`jheinecke/conllueditor:2.7.5` or `jheinecke/conllueditor:latest`). Thanks for hinting to the glitch in the README, you are right, it's  `docker run [...] jheinecke/conllueditor:latest`. I corrected it here and on docker.hub (and corrected another bug concerning the Port). Should be working now!

**Comment by gnegrelli** [comment]
It is working fine now! Thanks a million, @jheinecke .

One more question. Is it possible to use the file comparison mode with the docker image? Which parameters do i have to pass on `docker run` to do so?

**Comment by jheinecke** [comment]
not yet, but I'll check how to add it

**Comment by jheinecke** [comment]
Hi please check v2.8.0, its docker image allows the `--compare` option

**Comment by gnegrelli** [comment]
Thanks again, @jheinecke !
